---
title: "IJohnson Mod04 QFISH Assignment"
author: "Ivanya Johnson"
date: "20-09-2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# QFish Shark Control Program Data

To download data go to:
https://qfish.fisheries.qld.gov.au/query/number-caught-by-area-calendar-year-and-species-group/table


## Install and Load Packages

Be sure to install the following packages if they are not already installed.
```{r Packages}
# install.packages("janitor")

library(janitor)
library(tidyverse)
library(readr)
```


## Load Data
```{r}
totalcatch <- # Name data frame
  read_csv("Shark Catch.csv") |> # Select data to import
  row_to_names(row_number = 1) |> # Select the row to use for variable names of data frame.
  clean_names() # Creates unique names for the variables. If not included, R will give variables with common names the same name

totalcatch <- subset(totalcatch, select = )

head(totalcatch)
summary(totalcatch)
```


## Tidying Data

```{r}

```